import 'package:flutter/material.dart';
import 'package:flutterapp/testerapp/generatedloggedoutwidget/generated/GeneratedComponentWidget.dart';
import 'package:flutterapp/testerapp/generatedloggedoutwidget/generated/GeneratedButtonWidget1.dart';
import 'package:flutterapp/testerapp/generatedloggedoutwidget/generated/GeneratedShapeWidget.dart';
import 'package:flutterapp/testerapp/generatedloggedoutwidget/generated/GeneratedRectangleWidget5.dart';
import 'package:flutterapp/testerapp/generatedloggedoutwidget/generated/GeneratedRectangleWidget6.dart';
import 'package:flutterapp/testerapp/generatedloggedoutwidget/generated/GeneratedGroupWidget1.dart';
import 'package:flutterapp/testerapp/generatedloggedoutwidget/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/testerapp/generatedloggedoutwidget/generated/GeneratedRegisterWidget.dart';
import 'package:flutterapp/testerapp/generatedloggedoutwidget/generated/GeneratedStatusBarWidget.dart';

/* Frame Logged out
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoggedoutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget(),
              ),
              Positioned(
                left: 243.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 21.0,
                child: GeneratedRegisterWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 727.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 52.0,
                child: GeneratedButtonWidget(),
              ),
              Positioned(
                left: 192.0,
                top: 727.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 52.0,
                child: GeneratedButtonWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 707.0,
                child: GeneratedRectangleWidget6(),
              ),
              Positioned(
                left: 120.0,
                top: 799.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 5.0,
                child: GeneratedShapeWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 206.00001525878906,
                height: 54.0,
                child: GeneratedGroupWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 659.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 28.0,
                child: GeneratedComponentWidget(),
              )
            ]),
      ),
    ));
  }
}
