import 'package:flutter/material.dart';
import 'package:flutterapp/testerapp/generatedregisterstep1widget/generated/GeneratedComponentWidget2.dart';
import 'package:flutterapp/testerapp/generatedregisterstep1widget/generated/GeneratedUnionWidget6.dart';
import 'package:flutterapp/testerapp/generatedregisterstep1widget/generated/GeneratedRectangleWidget7.dart';
import 'package:flutterapp/testerapp/generatedregisterstep1widget/generated/GeneratedStatusBarWidget1.dart';
import 'package:flutterapp/testerapp/generatedregisterstep1widget/generated/GeneratedRegisterWidget2.dart';
import 'package:flutterapp/testerapp/generatedregisterstep1widget/generated/GeneratedComponentWidget1.dart';
import 'package:flutterapp/testerapp/generatedregisterstep1widget/generated/GeneratedButtonWidget2.dart';
import 'package:flutterapp/testerapp/generatedregisterstep1widget/generated/GeneratedKeyboardWidget.dart';

/* Frame Register (step 1)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterstep1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget7(),
              ),
              Positioned(
                left: 16.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 40.0,
                child: GeneratedRegisterWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedComponentWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedComponentWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedButtonWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedKeyboardWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 12.207107543945312,
                height: 11.353558540344238,
                child: GeneratedUnionWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget1(),
              )
            ]),
      ),
    ));
  }
}
