import 'package:flutter/material.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedRevShawnWidget.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedBethWilliamsWidget.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedBackgroundWidget145.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedEllipseWidget17.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedEllipseWidget19.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedBackgroundWidget144.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedEllipseWidget18.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedWillKennyWidget.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedStatusBarWidget9.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedRectangleWidget20.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedImlookingfortipsaroundcapturingthemilkywayIhavea6Dwitha.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedWantedtoaskifyoureavailableforaportraitshootnextweekWid.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedIknowImtryingtogetthefundsWidget.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedGroupWidget2.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedTabBarWidget4.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedBackgroundWidget142.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedBackgroundWidget143.dart';
import 'package:flutterapp/testerapp/generatedchatswidget/generated/GeneratedNavigationBarWidget1.dart';

/* Frame Chats
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget20(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedNavigationBarWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 0.5,
                child: GeneratedBackgroundWidget142(),
              ),
              Positioned(
                left: 0.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 0.5,
                child: GeneratedBackgroundWidget143(),
              ),
              Positioned(
                left: 0.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 0.5,
                child: GeneratedBackgroundWidget144(),
              ),
              Positioned(
                left: 0.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 0.5,
                child: GeneratedBackgroundWidget145(),
              ),
              Positioned(
                left: 16.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 64.0,
                child: GeneratedGroupWidget2(),
              ),
              Positioned(
                left: 96.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 38.0,
                child: GeneratedIknowImtryingtogetthefundsWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 20.0,
                child: GeneratedWillKennyWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 38.0,
                child:
                    GeneratedImlookingfortipsaroundcapturingthemilkywayIhavea6Dwitha(),
              ),
              Positioned(
                left: 96.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 20.0,
                child: GeneratedBethWilliamsWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 429.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 38.0,
                child:
                    GeneratedWantedtoaskifyoureavailableforaportraitshootnextweekWid(),
              ),
              Positioned(
                left: 96.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 20.0,
                child: GeneratedRevShawnWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedEllipseWidget17(),
              ),
              Positioned(
                left: 16.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedEllipseWidget18(),
              ),
              Positioned(
                left: 16.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedEllipseWidget19(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedTabBarWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget9(),
              )
            ]),
      ),
    ));
  }
}
