import 'package:flutter/material.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedAfast50mmlikef18wouldhelpwiththebokehIvebeenusingprimes.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedEllipseWidget11.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedThankyouThatwasveryhelpfulWidget.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedRectangle22Widget3.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedNavigationBarWidget.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedEllipseWidget13.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedStatusBarWidget8.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedEllipseWidget12.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedRectangleWidget18.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedReallyloveyourmostrecentphotoIvebeentryingtocapturethes.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedRectangle21Widget11.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedRectangle2Widget25.dart';
import 'package:flutterapp/testerapp/generatedindividualchatwidget/generated/GeneratedTabBarWidget3.dart';

/* Frame Individual chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIndividualchatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget18(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedNavigationBarWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedEllipseWidget11(),
              ),
              Positioned(
                left: 331.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedEllipseWidget12(),
              ),
              Positioned(
                left: 60.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 84.0,
                child: GeneratedRectangle2Widget25(),
              ),
              Positioned(
                left: 76.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 54.0,
                child:
                    GeneratedReallyloveyourmostrecentphotoIvebeentryingtocapturethes(),
              ),
              Positioned(
                left: 16.0,
                top: 338.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedEllipseWidget13(),
              ),
              Positioned(
                left: 60.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 50.0,
                child: GeneratedRectangle22Widget3(),
              ),
              Positioned(
                left: 76.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 20.0,
                child: GeneratedThankyouThatwasveryhelpfulWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 84.0,
                child: GeneratedRectangle21Widget11(),
              ),
              Positioned(
                left: 32.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 54.0,
                child:
                    GeneratedAfast50mmlikef18wouldhelpwiththebokehIvebeenusingprimes(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedTabBarWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget8(),
              )
            ]),
      ),
    ));
  }
}
